//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operations
    {
        public int OperationID { get; set; }
        public string InID { get; set; }
        public string OutID { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime OperationTime { get; set; }
    
        public virtual Card Card { get; set; }
        public virtual Card Card1 { get; set; }
    }
}
